### ISSUE TITLE
Core dump

### ISSUE THREAD

**Issue by Danile71** [TablePlus/TablePlus-Linux#196]
### Please answer the questions below, it helps us to track the issue.

1. Docker postgres:latest :

2. 0.1.240:

3. LinuxMint 21.3 (Ubuntu 22.04): 

4. Open new SQL query tab and exec any query:

example
```
SELECT id FROM jobs LIMIT 1;
```

strace
```
write(25, "INSERT INTO \"table_name\""..., 888) = 888
statx(25, "", AT_STATX_SYNC_AS_STAT|AT_EMPTY_PATH, STATX_MTIME, {stx_mask=STATX_BASIC_STATS|STATX_MNT_ID, stx_attributes=0, stx_mode=S_IFREG|0664, stx_size=888, ...}) = 0
close(25)                               = 0
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0x2c} ---
+++ killed by SIGSEGV (core dumped) +++

```

gdb
```
[Thread 0x7f228cf70640 (LWP 24167) exited]
[Thread 0x7f2276eac640 (LWP 24149) exited]

Thread 1 "tableplus" received signal SIGSEGV, Segmentation fault.
0x0000557d11c547c8 in table_plus_layouts_query_view_save_data (self=0x557d16f8e990) at ../src/Layouts/QueryView.vala:365

(gdb) bt
#0  0x0000557d11c547c8 in table_plus_layouts_query_view_save_data (self=0x557d16f8e990) at ../src/Layouts/QueryView.vala:365
#1  0x0000557d11c54d4a in table_plus_layouts_query_view_save_and_run_queries (self=0x557d16f8e990, queries=0x557d17044ec0) at ../src/Layouts/QueryView.vala:381
#2  0x0000557d11c518a2 in __lambda98_ (self=0x557d16f8e990, queries=0x557d17044ec0, message=0x557d1725ee70 "", ok=1) at ../src/Layouts/QueryView.vala:95
#3  0x0000557d11c518ed in ___lambda98__table_plus_services_safe_mode_service_on_send_statements (_sender=0x557d16ad1340, queries=0x557d17044ec0, message=0x557d1725ee70 "", ok=1, self=0x557d16f8e990) at ../src/Layouts/QueryView.vala:93
#4  0x0000557d11cf7fad in g_cclosure_user_marshal_VOID__BOXED_STRING_BOOLEAN (closure=0x557d16c63650, return_value=0x0, n_param_values=4, param_values=0x7fff6bb7bc20, invocation_hint=0x7fff6bb7bba0, marshal_data=0x0) at ../src/Services/SafeModeService.vala:1
#5  0x00007f2298299d2f in g_closure_invoke () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#6  0x00007f22982b5c36 in  () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#7  0x00007f22982b7614 in g_signal_emit_valist () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#8  0x00007f22982b7863 in g_signal_emit () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#9  0x0000557d11cf6691 in ___lambda500_ (_data116_=0x557d16b29660, password=0x557d16ce9390 "") at ../src/Services/SafeModeService.vala:11
#10 0x0000557d11cf6708 in ____lambda500__table_plus_layouts_safe_mode_confirm_dialog_unlock_safe_mode (_sender=0x557d16b0e300, password=0x557d16ce9390 "", self=0x557d16b29660) at /home/u/Documents/vala/tableplus-ui/build/SafeModeService.c:660
#11 0x0000557d11c8072b in g_cclosure_user_marshal_BOOLEAN__STRING (closure=0x557d16c91310, return_value=0x7fff6bb7c2a0, n_param_values=2, param_values=0x7fff6bb7c180, invocation_hint=0x7fff6bb7c100, marshal_data=0x0) at ../src/Layouts/SafeModeConfirmDialog.vala:1
#12 0x00007f2298299d2f in g_closure_invoke () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#13 0x00007f22982b5c36 in  () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#14 0x00007f22982b7026 in g_signal_emit_valist () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#15 0x00007f22982b7863 in g_signal_emit () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#16 0x0000557d11c80083 in table_plus_layouts_safe_mode_confirm_dialog_on_response (self=0x557d16b0e300, source=0x557d16b0e300, response_id=1) at ../src/Layouts/SafeModeConfirmDialog.vala:161
#17 0x0000557d11c80777 in _table_plus_layouts_safe_mode_confirm_dialog_on_response_gtk_dialog_response (_sender=0x557d16b0e300, response_id=1, self=0x557d16b0e300) at ../src/Layouts/SafeModeConfirmDialog.vala:43
#18 0x00007f2298298056 in g_cclosure_marshal_VOID__INTv () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#19 0x00007f22982b7700 in g_signal_emit_valist () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#20 0x00007f22982b7863 in g_signal_emit () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#21 0x00007f22982b7700 in g_signal_emit_valist () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#22 0x00007f22982b7863 in g_signal_emit () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#23 0x00007f22988c3aa0 in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#24 0x00007f22982b7700 in g_signal_emit_valist () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#25 0x00007f22982b7863 in g_signal_emit () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#26 0x00007f22988c3874 in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#27 0x00007f2298b76be5 in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#28 0x00007f22982b7700 in g_signal_emit_valist () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#29 0x00007f22982b7863 in g_signal_emit () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#30 0x00007f229898dffc in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#31 0x00007f229829e866 in g_cclosure_marshal_VOID__BOXEDv () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#32 0x00007f22982b7700 in g_signal_emit_valist () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#33 0x00007f22982b7863 in g_signal_emit () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#34 0x00007f2298985acb in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#35 0x00007f229898d83b in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#36 0x00007f229898e443 in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#37 0x00007f2298954f90 in gtk_event_controller_handle_event () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#38 0x00007f2298b26045 in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#39 0x00007f2298b6ceb8 in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#40 0x00007f22982b7700 in g_signal_emit_valist () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#41 0x00007f22982b7863 in g_signal_emit () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#42 0x00007f2298b34724 in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#43 0x00007f22989d7680 in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#44 0x00007f22989d852a in gtk_main_do_event () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#45 0x00007f22986b8743 in  () at /lib/x86_64-linux-gnu/libgdk-3.so.0
#46 0x00007f22986eff56 in  () at /lib/x86_64-linux-gnu/libgdk-3.so.0
#47 0x00007f22981a0d3b in g_main_context_dispatch () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#48 0x00007f22981f6258 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#49 0x00007f229819e3e3 in g_main_context_iteration () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#50 0x00007f22983c7fb5 in g_application_run () at /lib/x86_64-linux-gnu/libgio-2.0.so.0
#51 0x0000557d11bb9551 in _vala_main (args=0x7fff6bb7db08, args_length1=1) at ../src/Main.vala:9
#52 0x0000557d11bb9598 in main (argc=1, argv=0x7fff6bb7db08) at ../src/Main.vala:3
```

**Comment by Danile71** [comment]
Temporary fix
Download https://deb.tableplus.com/rpm/x86_64/tableplus-1.0.3-238.x86_64.rpm
Unpack and run tableplus

**Comment by huyphams** [comment]
Hi @Danile71 please upgrade to our latest release 242 it should fix the issue. Thanks!
